Prevent build from trying to use network
Debian builds run in a hermetic environment that has no network access.
Modify `ognibuild` to use the version in Debian archives instead of
downloading anything over the network.

This fixes the error:

    running build_ext
    running build_rust
        Updating git repository `https://github.com/jelmer/ognibuild`
    warning: spurious network error (3 tries remaining): [7] Could not connect to server (Failed to connect to github.com port 443 via 127.0.0.1 after 0 ms: Could not connect to server); class=Net (12)
    warning: spurious network error (2 tries remaining): [7] Could not connect to server (Failed to connect to github.com port 443 via 127.0.0.1 after 0 ms: Could not connect to server); class=Net (12)
    warning: spurious network error (1 tries remaining): [7] Could not connect to server (Failed to connect to github.com port 443 via 127.0.0.1 after 0 ms: Could not connect to server); class=Net (12)
    error: failed to get `ognibuild` as a dependency of package `debianize v0.163.0 (/builds/otto/lintian-brush/debian/output/source_dir/debianize)`
    Caused by:
      failed to load source for dependency `ognibuild`
    Caused by:
      Unable to update https://github.com/jelmer/ognibuild
    Caused by:
      failed to clone into: /builds/otto/lintian-brush/debian/output/source_dir/debian/cargo_home/git/db/ognibuild-8ae6b290ed25f576
    Caused by:
      network failure seems to have happened
      if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
      https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
    Caused by:
      [7] Could not connect to server (Failed to connect to github.com port 443 via 127.0.0.1 after 0 ms: Could not connect to server); class=Net (12)
    error: `cargo metadata --manifest-path debianize/Cargo.toml --format-version 1` failed with code 101
    -- Output captured from stdout:
    ERROR Backend subprocess exited when trying to invoke build_wheel